/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_guardianproject_f5android_plugins_f5_F5Buffers */

#ifndef _Included_info_guardianproject_f5android_plugins_f5_F5Buffers
#define _Included_info_guardianproject_f5android_plugins_f5_F5Buffers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    initImage
 * Signature: ([I[I[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_initImage
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    initCoeffs
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_initCoeffs
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    initHuffmanBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_initHuffmanBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    initHuffmanDecodeBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_initHuffmanDecodeBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    initPermutation
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_initPermutation
  (JNIEnv *, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setPixelValues
 * Signature: (Ljava/nio/ByteBuffer;[III)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setPixelValues
  (JNIEnv *, jobject, jobject, jintArray, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getPixelValue
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getPixelValue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setYValues
 * Signature: (Ljava/nio/ByteBuffer;FII)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setYValues
  (JNIEnv *, jobject, jobject, jfloat, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getYValue
 * Signature: (Ljava/nio/ByteBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getYValue
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setCr1Values
 * Signature: (Ljava/nio/ByteBuffer;FII)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setCr1Values
  (JNIEnv *, jobject, jobject, jfloat, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getCr1Value
 * Signature: (Ljava/nio/ByteBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getCr1Value
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setCb1Values
 * Signature: (Ljava/nio/ByteBuffer;FII)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setCb1Values
  (JNIEnv *, jobject, jobject, jfloat, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getCb1Value
 * Signature: (Ljava/nio/ByteBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getCb1Value
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setCr2Values
 * Signature: (Ljava/nio/ByteBuffer;FII)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setCr2Values
  (JNIEnv *, jobject, jobject, jfloat, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getCr2Value
 * Signature: (Ljava/nio/ByteBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getCr2Value
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setCb2Values
 * Signature: (Ljava/nio/ByteBuffer;FII)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setCb2Values
  (JNIEnv *, jobject, jobject, jfloat, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getCb2Value
 * Signature: (Ljava/nio/ByteBuffer;II)F
 */
JNIEXPORT jfloat JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getCb2Value
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setCoeffValues
 * Signature: (Ljava/nio/ByteBuffer;[III)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setCoeffValues
  (JNIEnv *, jobject, jobject, jintArray, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getCoeffValue
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getCoeffValue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setHuffmanBufferValues
 * Signature: (Ljava/nio/ByteBuffer;[III)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setHuffmanBufferValues
  (JNIEnv *, jobject, jobject, jintArray, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getHuffmanBufferValue
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getHuffmanBufferValue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setHuffmanDecodeBufferValues
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setHuffmanDecodeBufferValues
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getHuffmanDecodeBufferValue
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getHuffmanDecodeBufferValue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    setPermutationValues
 * Signature: (Ljava/nio/ByteBuffer;[III)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_setPermutationValues
  (JNIEnv *, jobject, jobject, jintArray, jint, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    getPermutationValue
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_getPermutationValue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    cleanUpImage
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_cleanUpImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    cleanUpCoeffs
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_cleanUpCoeffs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    cleanUpHuffmanBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_cleanUpHuffmanBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    cleanUpHuffmanDecodeBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_cleanUpHuffmanDecodeBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_guardianproject_f5android_plugins_f5_F5Buffers
 * Method:    cleanUpPermutation
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_info_guardianproject_f5android_plugins_f5_F5Buffers_cleanUpPermutation
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
